name: Deploy Frontend to VM

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: List root directory after checkout
        run: ls -l

      - name: Ensure Frontend directory exists
        run: mkdir -p Frontend

      - name: Create .env file
        run: |
          echo "REACT_APP_API_BASE_URL=${{ secrets.REACT_APP_API_BASE_URL }}" > Frontend/.env

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci
        working-directory: ./Frontend

      - name: Build React app
        run: npm run build
        working-directory: ./Frontend

      - name: List root directory after build
        run: ls -l

      - name: List build directory in root
        run: ls -l build || echo "No build directory in root."

      - name: Clean target directory on VM
        run: |
          sudo apt-get update && sudo apt-get install -y sshpass
          sshpass -p ${{ secrets.VM_PASSWORD }} ssh -o StrictHostKeyChecking=no ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }} "rm -rf /home/${{ secrets.VM_USER }}/frontend && mkdir -p /home/${{ secrets.VM_USER }}/frontend"

      - name: Create nginx config script
        run: |
          cat > nginx-frontend-setup.sh <<'EOF'
          #!/bin/bash
          sudo apt-get update && sudo apt-get install -y nginx
          sudo tee /etc/nginx/sites-available/frontend > /dev/null <<EOC
          server {
              listen 80;
              server_name _;
              root /home/${{ secrets.VM_USER }}/frontend;
              index index.html;
              location / {
                  try_files \$uri /index.html;
              }
          }
          EOC
          sudo ln -sf /etc/nginx/sites-available/frontend /etc/nginx/sites-enabled/frontend
          sudo rm -f /etc/nginx/sites-enabled/default
          sudo chown -R www-data:www-data /home/${{ secrets.VM_USER }}/frontend
          sudo chmod -R 755 /home/${{ secrets.VM_USER }}/frontend
          sudo nginx -t
          EOF

      - name: Copy nginx config script to VM
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          password: ${{ secrets.VM_PASSWORD }}
          source: "nginx-frontend-setup.sh"
          target: "/home/${{ secrets.VM_USER }}/"

      - name: Run nginx config script on VM
        run: |
          sudo apt-get update && sudo apt-get install -y sshpass
          sshpass -p ${{ secrets.VM_PASSWORD }} ssh -o StrictHostKeyChecking=no ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }} 'bash /home/${{ secrets.VM_USER }}/nginx-frontend-setup.sh'

      - name: Copy build to VM
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          password: ${{ secrets.VM_PASSWORD }}
          source: "build/*"
          target: "/home/${{ secrets.VM_USER }}/frontend"

      - name: Restart nginx
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          password: ${{ secrets.VM_PASSWORD }}
          script: |
            sudo systemctl restart nginx 