name: Deploy Frontend to VM

on:
  push:
    branches:
      - master
      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: List root directory after checkout
        run: ls -l

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci
        working-directory: ./

      - name: Set production environment variables
        run: |
          echo "Setting up production environment variables..."
          echo "Backend URL will be configured for cross-server communication"
        working-directory: ./

      - name: Build React app
        run: npm run build
        working-directory: ./
        env:
          # Backend Server Configuration (for cross-server communication)
          REACT_APP_BASE_URL: ${{ secrets.BASE_URL }}
          REACT_APP_BACKEND_URL: ${{ secrets.BACKEND_URL }}
          
          # Client Configuration
          REACT_APP_CLIENT_URL: ${{ secrets.FRONTEND_URL }}
          
          # Environment
          NODE_ENV: production
          
          # Build Configuration
          GENERATE_SOURCEMAP: false
          REACT_APP_VERSION: 1.0.0
          
          # Debug Configuration
          REACT_APP_DEBUG: false
          REACT_APP_LOG_LEVEL: error
          
          # Feature Flags
          REACT_APP_ENABLE_SOCKET_IO: true
          REACT_APP_ENABLE_REAL_TIME_CHAT: true
          REACT_APP_ENABLE_AVATAR_CHAT: true
          REACT_APP_ENABLE_COMMUNITY_CHAT: true
          
          # External Services
          REACT_APP_GOOGLE_MAPS_API_KEY: ${{ secrets.GOOGLE_MAPS_API_KEY }}
          REACT_APP_GOOGLE_PLACES_API_KEY: ${{ secrets.GOOGLE_PLACES_API_KEY }}
          
          # Firebase Configuration
          REACT_APP_FIREBASE_API_KEY: ${{ secrets.FIREBASE_API_KEY }}
          REACT_APP_FIREBASE_AUTH_DOMAIN: ${{ secrets.FIREBASE_AUTH_DOMAIN }}
          REACT_APP_FIREBASE_PROJECT_ID: ${{ secrets.FIREBASE_PROJECT_ID }}
          REACT_APP_FIREBASE_STORAGE_BUCKET: ${{ secrets.FIREBASE_STORAGE_BUCKET }}
          REACT_APP_FIREBASE_MESSAGING_SENDER_ID: ${{ secrets.FIREBASE_MESSAGING_SENDER_ID }}
          REACT_APP_FIREBASE_APP_ID: ${{ secrets.FIREBASE_APP_ID }}
          REACT_APP_FIREBASE_MEASUREMENT_ID: ${{ secrets.FIREBASE_MEASUREMENT_ID }}

      - name: List root directory after build
        run: ls -l

      - name: List build directory in root
        run: ls -l build || echo "No build directory in root."

      - name: Verify build directory exists
        run: |
          if [ ! -d "build" ]; then
            echo "ERROR: Build directory does not exist!"
            echo "Current directory contents:"
            ls -la
            exit 1
          else
            echo "Build directory exists and contains:"
            ls -la build/
          fi

      - name: Clean target directory on VM
        run: |
          sudo apt-get update && sudo apt-get install -y sshpass
          sshpass -p ${{ secrets.VM_PASSWORD }} ssh -o StrictHostKeyChecking=no -o ConnectTimeout=30 -o ServerAliveInterval=60 -o ServerAliveCountMax=3 ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }} "rm -rf /home/${{ secrets.VM_USER }}/frontend/*" || true

      - name: Ensure frontend directory exists on VM
        run: |
          sudo apt-get update && sudo apt-get install -y sshpass
          sshpass -p ${{ secrets.VM_PASSWORD }} ssh -o StrictHostKeyChecking=no -o ConnectTimeout=30 -o ServerAliveInterval=60 -o ServerAliveCountMax=3 ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }} 'mkdir -p /home/${{ secrets.VM_USER }}/frontend'

      - name: Create nginx config script
        run: |
          cat > nginx-frontend-setup.sh <<'EOF'
          #!/bin/bash
          sudo apt-get update && sudo apt-get install -y nginx
          
          # Create SSL directory if it doesn't exist
          sudo mkdir -p /etc/ssl/certs /etc/ssl/private
          
          # Install certbot for Let's Encrypt (optional)
          sudo apt-get install -y certbot python3-certbot-nginx || echo "Certbot installation skipped"
          
          # Write SSL certificate if provided
          if [ ! -z "${{ secrets.SSL_CERTIFICATE }}" ]; then
            echo '${{ secrets.SSL_CERTIFICATE }}' | sudo tee /etc/ssl/certs/frontend.crt > /dev/null
            echo "SSL certificate created successfully"
          fi
          
          # Write SSL private key if provided
          if [ ! -z "${{ secrets.SSL_PRIVATE_KEY }}" ]; then
            echo '${{ secrets.SSL_PRIVATE_KEY }}' | sudo tee /etc/ssl/private/frontend.key > /dev/null
            sudo chmod 600 /etc/ssl/private/frontend.key
            echo "SSL private key created successfully"
          fi
          
          # Create nginx configuration
          if [ ! -z "${{ secrets.SSL_CERTIFICATE }}" ] && [ ! -z "${{ secrets.SSL_PRIVATE_KEY }}" ]; then
            # HTTPS configuration
            sudo tee /etc/nginx/sites-available/frontend > /dev/null <<EOC
          server {
              listen 80;
              server_name _;
              return 301 https://\$server_name\$request_uri;
          }
          
          server {
              listen 443 ssl http2;
              server_name _;
              
              ssl_certificate /etc/ssl/certs/frontend.crt;
              ssl_certificate_key /etc/ssl/private/frontend.key;
              ssl_protocols TLSv1.2 TLSv1.3;
              ssl_ciphers ECDHE-RSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384;
              ssl_prefer_server_ciphers off;
              
              root /home/${{ secrets.VM_USER }}/frontend;
              index index.html;
              
              location / {
                  try_files \$uri /index.html;
              }
          }
          EOC
            echo "HTTPS configuration created"
          else
            # HTTP only configuration
            sudo tee /etc/nginx/sites-available/frontend > /dev/null <<EOC
          server {
              listen 80;
              server_name _;
              root /home/${{ secrets.VM_USER }}/frontend;
              index index.html;
              location / {
                  try_files \$uri /index.html;
              }
          }
          EOC
            echo "HTTP configuration created"
          fi
          
          sudo ln -sf /etc/nginx/sites-available/frontend /etc/nginx/sites-enabled/frontend
          sudo rm -f /etc/nginx/sites-enabled/default
          sudo chown -R www-data:www-data /home/${{ secrets.VM_USER }}/frontend
          sudo chmod -R 755 /home/${{ secrets.VM_USER }}/frontend
          sudo nginx -t
          EOF

      - name: Remove existing nginx script directory on VM
        run: |
          sudo apt-get update && sudo apt-get install -y sshpass
          sshpass -p ${{ secrets.VM_PASSWORD }} ssh -o StrictHostKeyChecking=no -o ConnectTimeout=30 -o ServerAliveInterval=60 -o ServerAliveCountMax=3 ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }} 'rm -rf /home/${{ secrets.VM_USER }}/nginx-frontend-setup.sh' || true

      - name: Copy nginx config script to VM
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          password: ${{ secrets.VM_PASSWORD }}
          source: "nginx-frontend-setup.sh"
          target: "/home/${{ secrets.VM_USER }}/"
          overwrite: true
          timeout: 30s

      - name: Run nginx config script on VM
        run: |
          sudo apt-get update && sudo apt-get install -y sshpass
          sshpass -p ${{ secrets.VM_PASSWORD }} ssh -o StrictHostKeyChecking=no -o ConnectTimeout=30 -o ServerAliveInterval=60 -o ServerAliveCountMax=3 ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }} 'bash /home/${{ secrets.VM_USER }}/nginx-frontend-setup.sh'

      - name: Set permissions on target directory
        run: |
          sudo apt-get update && sudo apt-get install -y sshpass
          sshpass -p ${{ secrets.VM_PASSWORD }} ssh -o StrictHostKeyChecking=no -o ConnectTimeout=30 -o ServerAliveInterval=60 -o ServerAliveCountMax=3 ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }} 'sudo chown -R ${{ secrets.VM_USER }}:${{ secrets.VM_USER }} /home/${{ secrets.VM_USER }}/frontend && sudo chmod -R 755 /home/${{ secrets.VM_USER }}/frontend'

      - name: Copy build to VM
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          password: ${{ secrets.VM_PASSWORD }}
          source: "build/"
          target: "/home/${{ secrets.VM_USER }}/frontend"
          strip_components: 1
          timeout: 60s

      - name: Restart nginx
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          password: ${{ secrets.VM_PASSWORD }}
          script: |
            sudo systemctl restart nginx
          timeout: 30s 

# Required secrets:
# VM_HOST: The public IP of your Azure VM (from Terraform output)
# VM_USER: The admin username for your VM (e.g., azureuser)
# VM_PASSWORD: The admin password for your VM
# BASE_URL: Your backend API base URL
# BACKEND_URL: Your backend server URL
# FRONTEND_URL: Your frontend URL
# GOOGLE_MAPS_API_KEY: Your Google Maps API key
# GOOGLE_PLACES_API_KEY: Your Google Places API key
# FIREBASE_API_KEY: Your Firebase API key
# FIREBASE_AUTH_DOMAIN: Your Firebase auth domain
# FIREBASE_PROJECT_ID: Your Firebase project ID
# FIREBASE_STORAGE_BUCKET: Your Firebase storage bucket
# FIREBASE_MESSAGING_SENDER_ID: Your Firebase messaging sender ID
# FIREBASE_APP_ID: Your Firebase app ID
# FIREBASE_MEASUREMENT_ID: Your Firebase measurement ID

# Optional SSL secrets (for HTTPS):
# SSL_CERTIFICATE: Your SSL certificate content (.crt or .pem file content)
# SSL_PRIVATE_KEY: Your SSL private key content (.key file content)

# SSL Features:
# - Automatically configures HTTPS if SSL secrets are provided
# - Redirects HTTP to HTTPS
# - Uses modern SSL protocols (TLS 1.2/1.3)
# - Secure cipher configuration
# - Falls back to HTTP-only if no SSL secrets 
